const DAY=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'], WEEK=10080;
function weekly(start,end){const a=new Date(start),b=new Date(end);if(!Number.isFinite(+a)||!Number.isFinite(+b))return null;const st=a.getUTCDay()*1440+a.getUTCHours()*60+a.getUTCMinutes();return {day:a.getUTCDay(),startMinute:st,endMinute:st+Math.min(1440,Math.max(1,Math.round((b-a)/60000)))}}
function normalize(s){if(s.weekly)return s;const start=s.startTime||s.start_time,end=s.endTime||s.end_time,w=weekly(start,end);return w?{...s,startTime:start,endTime:end,weekly:w}:null}
function pub(raw=[]){return raw.map(s=>normalize({startTime:s.start_time,endTime:s.end_time,category:s.category||null,title:s.title||'',isRecurring:Boolean(s.is_recurring)})).filter(Boolean)}
function obs(raw=[]){return raw.map(s=>normalize({startTime:s.startTime,endTime:s.endTime,title:'Observed',isRecurring:false})).filter(Boolean)}
function ov(a,b){let n=0;for(const shift of [-WEEK,0,WEEK])n+=Math.max(0,Math.min(a.endMinute,b.endMinute+shift)-Math.max(a.startMinute,b.startMinute+shift));return n}
export function scheduleProfile(published=[],observed=[]){const p=pub(published);if(p.length)return{type:'published',segments:p,confidence:95,evidence:`${p.length} published segment${p.length===1?'':'s'}`};const o=obs(observed);return{type:'observed',segments:o,confidence:o.length?Math.min(85,45+o.length*5):0,evidence:o.length?`${o.length} observed timing samples`:'No schedule evidence'}}
export function scheduleCompatibility(mine,theirs){const A=(mine?.segments||[]).map(normalize).filter(Boolean),B=(theirs?.segments||[]).map(normalize).filter(Boolean);let mins=0;for(const a of A)for(const b of B)mins+=ov(a.weekly,b.weekly);const shared=[...new Set(A.map(x=>x.weekly.day))].filter(d=>B.some(x=>x.weekly.day===d));const deltas=[];for(const a of A)for(const b of B)if(a.weekly.day===b.weekly.day)deltas.push(Math.abs(a.weekly.startMinute-b.weekly.startMinute));const closest=deltas.length?Math.min(...deltas):null;const overlap=Math.min(100,Math.min(mins,240)/240*100),days=Math.min(100,Math.min(shared.length,3)/3*100),prox=closest===null?0:Math.max(0,100-closest/180*100),evidence=Math.min(mine?.confidence??80,theirs?.confidence??80)/100;return{score:Math.round((overlap*.60+days*.20+prox*.20)*(.65+.35*evidence)),overlapMinutes:Math.round(mins),sharedDays:shared.map(d=>DAY[d]),closestStartMinutes:closest,myEvidence:mine?.type||'unknown',theirEvidence:theirs?.type||'unknown',myConfidence:mine?.confidence??0,theirConfidence:theirs?.confidence??0}}
export function formatOverlap(r){if(!r?.overlapMinutes)return'No direct weekly overlap';const h=Math.floor(r.overlapMinutes/60),m=r.overlapMinutes%60;return`${h?h+'h ':''}${m?m+'m ':''}overlap • ${r.sharedDays.join(', ')}`.trim()}

export function weeklyWindows(profile){return (profile?.segments||[]).map(s=>({day:s.weekly.day,start:s.weekly.startMinute%1440,end:s.weekly.endMinute%1440,title:s.title||'',source:profile.type}))}
export function findCommonWindows(profiles=[],minimumMinutes=60){const out=[];for(let day=0;day<7;day++){const ps=profiles.map(p=>weeklyWindows(p).filter(w=>w.day===day));if(ps.some(x=>!x.length))continue;for(const seed of ps[0])for(let start=seed.start;start<seed.end;start+=30){let end=seed.end,ok=true;for(const wins of ps.slice(1)){const hit=wins.find(w=>w.start<=start&&w.end>start);if(!hit){ok=false;break}end=Math.min(end,hit.end)}if(ok&&end-start>=minimumMinutes)out.push({day,start,end,minutes:end-start})}}const dedup=[];for(const w of out.sort((a,b)=>b.minutes-a.minutes)){if(!dedup.some(x=>x.day===w.day&&Math.abs(x.start-w.start)<30))dedup.push(w)}return dedup.slice(0,10)}
